# Вектора


## Back to school

В геометрии вектор — направленный отрезок прямой, то есть отрезок, для которого указано, какая из его граничных точек является началом, а какая — концом

![alt](./vector.jpg "Вектор")

## Линейная алгебра

Вектор - математическая структура, которая представляет собой набор элементов, называемых векторами, для которых определены операции сложения друг с другом и умножения на число — скаляр

$x=(2,3,4)$

![alt](./space.jpg "Вектор в пространстве")

In [2]:
import numpy as np

x = np.array([2,3,4])
print(x)

[2 3 4]


Размерность вектора количество "компонент" в этом векторе

К примеру, если мы рассмотрим вектор мутаций в геноме, то его размерность может быть несколько сотен тысяч

$mutations=(0,0,1,0,1,1,0,.....)$

In [3]:
print(x.shape)

(3,)


## Векторное  пространство

Векторное пространство - это множество векторов одной размерности, будем обозначать $\mathbb{V}$, которое обладает следующими свойствами:
* Заданы 2 замкнутые операции: сложение векторов и умножение вектора на скаляр(число)
* $x+y = y+x,\  \forall x,y \in \mathbb{V}$
* $x+(y+z)=(x+y)+z,\ \forall x,y,z \in \mathbb{V}$
* $\exists 0 \in \mathbb{V}: x+0=x,\ \forall x \in \mathbb{V}$
* $\forall x \in \mathbb{V}\ \exists -x \in \mathbb{V}: x+(-x)=0$
* $\alpha(\beta x) = (\alpha \beta)x$
* $1 x = x$
* $(\alpha + \beta)x = \alpha x + \beta x$
* $\alpha (x+y)=\alpha x + \alpha y$

В рамках курса будем говорить о евклидовых пространствах: $\mathbb{R}^n$

## Сложение векторов
$a=(a_1, a_2, ..., a_n)$

$b=(b_1, b_2, ..., b_n)$

$a+b=(a_1+b_1, a_2+b_2, ..., a_n+b_n)$

![alt](./sum.jpg "Сложение векторов")

In [4]:
x = np.array([2,3,4])
y = np.array([1,1,1])

print(x+y)

[3 4 5]


## Умножение вектора на скаляр
$a=(a_1,a_2,...,a_n)$

$\beta a=(\beta a_1, \beta a_2, ..., \beta a_3)$

![alt](./scalar.jpg "Скалярное умножение")

In [8]:
x = np.array([2,3,4])
beta = 2
print(beta*x)


[4 6 8]


Интересный вывод: если вы возьмете выборку из m векторов, то можно найти средний вектор:

$\bar{x}=\frac{1}{m}\sum_{i=1}^{m}(x_1^i, x_2^i, ..., x_n^i)$

## Линейная независимость - информация в векторах

Пусть вектор x отображает информацию о тарифе пользователя:
* Стоимость одной минуты
* Стоимость одного SMS
* Стоимость МБ данных
* Стоимость ГБ данных
* Расход за первый квартал
* Расход за второй квартал
* Расход за третий квартал
* Расход за четвертый квартал
* Расход за год

$x_1 = (.3, .1, 0.01, 10.24, 300, 200, 100, 50, 650)$

$x_2 = (.5, .7, 0.02, 20.48, 100, 200, 500, 0, 800)$

$x_3 = (.1, .0, 0.1, 102.4, 900, 900, 900, 900, 3600)$

**Линейная зависимость**:

$\beta_1 x_1 + \beta_2 x_2 + .... + \beta_3 x3 = 0$, где $\exists \beta \neq 0$,

**Линейная зависимость вектора**:

$x_i = \beta_1 x_1 + \beta_2 x_2 + ... + \beta_{i-1} x_{i-1} + \beta_{i+1} x_{i+1} + ... + \beta_n x_n$

$dim V$ - максимальное число линейно независимых векторов в пространстве

![alt](./basis.png "Базис пространства")

$e_1=(1,0,0)\ e_2=(0,1,0)\ e_3=(0,0,1)$

## Норма вектора

$\| x \| = scalar$

$\| 0 \| = 0$

$\| {x+y} \| \leq \| x \| + \| y \|$

$\| {\alpha x} \| = \alpha \| x \|$

Евклидова норма
$\| x_2 \| = \sqrt{\sum_{i=1}^{2}x_i^2}$

![alt](./norm.jpg "Норма")

In [10]:
from numpy.linalg import norm

x = np.array([3,4])
print(norm(x))

5.0


# Метрика

$\rho(x,y) = \| {x-y} \|$

In [11]:
x = np.array([1,2,5])
y = np.array([-2,0,11])

print(norm(x-y))

7.0


## Скалярное произведение векторов

$x \cdot y = \sum_{i=1}^{n} x_i y_i$

$\| x \| = \sqrt{x \cdot x}$

$x \cdot y = \| x \| \| y \| cos(x,y)$

$cos(x,y) = \frac{x \cdot y}{\| x \| \| y \|}$

$cos(x,y) = 1$ - вектора лежат на одной прямой

$cos(x,y) = 0$ - ортоганальные вектора

In [21]:
x = np.array([1,0])
y = np.array([0,1])

print(np.dot(x,y))

0


In [23]:
x = np.array([12,-1])
y = np.array([3.1,8.9999])

cos_value = np.dot(x,y) / (norm(x) * norm(y))
print('Значение косинуса: ', cos_value)
print('Значение угла в радианах: ', np.arccos(cos_value))
print('Значение угла в градусах: ', np.degrees(np.arccos(cos_value)))

Значение косинуса:  0.2460270707098335
Значение угла в радианах:  1.322217135590574
Значение угла в градусах:  75.7574614692168


In [19]:
# PS - изменение размерности

x = np.array([1,2,3])
print('X=',x)
print('Shape=',x.shape)

x = x.reshape((1,3))
print('X=', x)
print('Shape=', x.shape)

X= [1 2 3]
Shape= (3,)
X= [[1 2 3]]
Shape= (1, 3)
